### ISSUE TITLE
Way to return tuple / struct type?

### ISSUE THREAD

**Issue by patniemeyer** [y-pakorn/flutter_web3#25]
I'm not seeing a way to use a tuple / struct value as a return type, e.g.:

`function read(address foo) external view returns (uint256, uint256)
`

As a workaround I'm just interpreting the dynammics as strings but I was wondering if I missed something.  Thanks.

**Comment by y-pakorn** [comment]
As mentioned in README, all tuple is consider `List` type. And because of dart:js [limitation](https://pub.dev/packages/js#:~:text=List%20instances%20coming%20from%20JavaScript%20will%20always%20be%20List%3Cdynamic%3E), `List` instances coming from JavaScript will always be `List<dynamic>`.

So your return type are `List<dynamic>` which first and second element is `BigNumber` type.
