### ISSUE TITLE
Cannot use contract.send() with nonpayable function

### ISSUE THREAD

**Issue by apegineer** [y-pakorn/flutter_web3#4]
![Screen Shot 2564-08-08 at 17 06 38](https://user-images.githubusercontent.com/85834004/128626972-1d33aac2-50f8-4674-b8fb-d46f779ca3ad.png)

When calling a nonpayable function that needs to write state using Contract.send(), it always returns the attached error. 

I think the error might be about that I need to assign the gas limit fee and not about being the owner as this is the contract I made and I double-check that I use the owner address to make a call.

I tried to change it to the function to a payable function and assign a gas fee limit and it worked.

When I assign a gas fee in the send for nonpayable function now, it returns the following:

![Screen Shot 2564-08-08 at 17 11 53](https://user-images.githubusercontent.com/85834004/128627069-337b7134-4cdb-4eb3-a0c3-b685ad1c92a2.png)

Any ideas?

**Comment by y-pakorn** [comment]
The transaction is being reverted is because of `Ownable: caller is not the owner`, not the gas estimation.

The gas estimation works by increasing the gas until the function can be run. If the function can't run through, i.e. being reverted by `require` or `assert`. The estimation will be increased so high that it got through blockchain's gas limit, then it will throw an error.

For the second question, the error state that you override the value of the transaction, not the gas limit or gas price. The non-payable function will naturally prevent override of the value.
